name: Poetry Setup including Cache with configurable files
description: This composite action loads the cache that can be configured for multiple files, installs poetry with configurations and it's packages if not found on the cache.

inputs:
  # Required
  files_to_cache:
    required: true
    description: The poetry installation is in '/home/runner/.local/' and the '.venv' is for the poetry packages
    default: |
      .venv
      /home/runner/.local/
  # Optional
  python_version:
    required: false
    default: 3.11.2
  poetry_version:
    required: false
    default: 1.8.4
  working_directory:
    required: false
    description: Whenever the django app (i.e. manage.py) is not in the root; the location can be specified here. The last slash needs to be included
    default: ./

runs:
  using: "composite"
  steps:
    - name: Load cache
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.files_to_cache }}
        key: cache-python-${{ inputs.python_version }}-poetry-${{ inputs.poetry_version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install Poetry ${{ inputs.poetry_version }}
      if: steps.cache.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry_version }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Configure Poetry and install packages
      working-directory: ${{ inputs.working_directory }}
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        poetry config repositories.repowered ${{ secrets.private_pypi_url}}
        poetry config http-basic.repowered ${{ secrets.private_pypi_user }} ${{ secrets.private_pypi_password}}
        poetry install --no-interaction --no-root --no-ansi