name: Run Django Unit Test with Coverage, Check the Migration, Run Sonar and Linting Quality Checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  django-unit-migration-test:
    uses: test-org-fanna/.github/.github/workflows/django-test-migrations-coverage.yml@main
    with:
      # python_versions: # Optional, defaults to "['3.11.2']"
      # poetry_cache_key: # Optional, for fresh installations, defaults to poetry-0

  quality-control-sonar:
    needs: django-unit-migration-test
    uses: test-org-fanna/.github/.github/workflows/quality-control-sonar.yml@main
    with:
      # coverage_report_name: # Optional, defaults to 'coverage.xml'
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  quality-control-python-lint:
    uses: test-org-fanna/.github/.github/workflows/quality-control-python-lint.yml@main
    with:
    # python_versions: # Optional, defaults to "['3.11.2']"