# Repowered analysis step 2 (ref: README.MD)
name: Step 2 - Docker build and push

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - qa
      - release/**
      - hotfix/**
      - main

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    matrix:
        # Add your Dockerfile name(s) in the list below
        # Standard use is just 'Dockerfile'
        dockerfile: [Dockerfile]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.dockerfile }} and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }q
          push: true
          tags: ${{ env.TAGS }}
          secrets: |
            PRIVATE_PYPI_URL=${{ secrets.PRIVATE_PYPI_URL }}
            PRIVATE_PYPI_USER=${{ secrets.PRIVATE_PYPI_USER}}
            PRIVATE_PYPI_PASSWORD=${{ secrets.PRIVATE_PYPI_PASSWORD }}
