name: GitHub Tag, Docker publish build, SSH Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - release/**
      - hotfix/**

jobs:
  tag:
    permissions:
      contents: write
    uses: Repowered/.github/.github/workflows/generate-github-tag.yml@main

  # Repeat steps docker + deploy-verify if there are multiple Dockerfiles

  docker:
    uses: Repowered/.github/.github/workflows/docker-build-and-push.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      docker_hub_username: ${{ vars.DOCKER_HUB_USERNAME }}
      # dockerfile_name: # Optional, defaults to 'Dockerfile'
    secrets:
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Optional (Current maximum of secrets that can be set =  6 secrets. Can be expanded)
      # docker_secret_1:
      # docker_secret_2:
      # docker_secret_3:
      # docker_secret_4:
      # docker_secret_5:
      # docker_secret_6:

  github-environment:
    uses: Repowered/.github/.github/workflows/determine-environment.yml@main

  setup-doctl:
    uses: Repowered/.github/.github/workflows/setup-doctl-kube.yml@main
    needs: github-environment
    with:
      environment: ${{ needs.github-environment.outputs.environment }}
    secrets: inherit

  deploy-verify:
    uses: Repowered/.github/.github/workflows/kube-deploy-verify.yml@main
    needs: [setup-doctl, docker]
    with:
      # If there are multiple deployments for a single docker image, the container names can be specified here
      # Example:
      # Dockerfile 'hello-world' is responsible for the following deployments: foo, bar
      # the corresponding container_names are: "['foo', 'bar']"
      container_names: # A JSON list string i.e. "['my name']"
      docker_image_tag: ${{ needs.docker.outputs.image_tag }}