name: Coverage Comment

on:
  workflow_call:
    inputs:
      # Optional
      coverage_report_name:
        type: string
        default: coverage.xml
    secrets:
      # Optional
      github-token:
        description: Standard availability during run-time via secrets.GITHUB_TOKEN
        required: false
        default: ${{ secrets.GITHUB_TOKEN }}

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.coverage_report_name }}

      - name: Coverage comment
        id: coverage-comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          MINIMUM_ORANGE: 80

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage-comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt





