name: Coverage Comment

on:
  workflow_call:
    inputs:
      # Optional
      coverage_report_name:
        type: string
        default: coverage.xml
      working_directory:
        type: string
        default: ./

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.coverage_report_name }}
          path: ${{ inputs.working_directory }}

      - name: Coverage comment
        id: coverage-comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MINIMUM_ORANGE: 80

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage-comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt





