name: Determine environment
# Since reusable workflows cannot handle environments:
# https://docs.github.com/en/enterprise-cloud@latest/actions/sharing-automations/reusing-workflows#limitations

on:
  workflow_call:
    outputs:
      environment:
        description: "The GitHub's environment"
        value: ${{ jobs.determine-environment.outputs.environment }}

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.get-env.outputs.environment }}
    steps:
      - name: Determine the GitHub Action environment
        id: get-env
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi