name: Docker build and push

on:
  workflow_call:
    inputs:
      # Required
      container_names:
        type: string
        required: true
        description: A JSON string list of all deployments belonging to the same (docker) image
      docker_image_tag:
        type: string
      environment:
        type: string
        required: true

jobs:
  deploy-verify:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        container_name: ${{ fromJSON(inputs.container_names) }}
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        env:
          expiry-seconds: ${{ vars.KUBE_CRED_EXPIRY_SECOND || 300 }}
        run: doctl kubernetes cluster kubeconfig save  --expiry-seconds ${{ env.expiry-seconds }} ${{ vars.CLUSTER_NAME }}

      - name: Update kubernetes secrets
        continue-on-error: true
        run: |
          kubectl delete secret infisical-secrets --ignore-not-found=true
          kubectl create secret generic infisical-secrets \
          --from-literal=INFISICAL_CLIENT_ID=${{ secrets.INFISICAL_CLIENT_ID }} \
          --from-literal=INFISICAL_CLIENT_SECRET=${{ secrets.INFISICAL_CLIENT_SECRET }} \
          --from-literal=INFISICAL_PROJECT_ID=${{ secrets.INFISICAL_PROJECT_ID }}

      - name: Deploy ${{matrix.container_name}}
        run: kubectl set image deployment/${{matrix.container_name}}-deployment ${{matrix.container_name}}=${{inputs.docker_image_tag}}

      - name: Verify ${{matrix.container_name}} deployment
        id: kube-deploy
        run: kubectl rollout status deployment/${{matrix.container_name}}-deployment

  deploy-summary:
    name: Deployment summary
    needs: [ deploy-verify ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          if [[ "${{ needs.deploy-verify.outcome }}" == "success" ]]; then
            echo "<h2>:check: Deployment successful </h2>" >> $GITHUB_STEP_SUMMARY
          else
            echo "<h2>:x: Deployment failed </h2>" >> $GITHUB_STEP_SUMMARY
          fi
          echo "Branch: $BRANCH" >> $GITHUB_STEP_SUMMARY
          echo "Image tag: ${{ inputs.docker_image_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "Environment: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "By: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
        env:
          BRANCH: ${{ github.event.workflow_run.head_branch || github.ref_name }}