name: Python Lint Quality Control

on:
  workflow_call:
    inputs:
      # Optional
      python_versions:
        type: string
        description: A JSON string list of all python versions to run these tests on
        default: "['3.11.2']"

jobs:
  quality-control-python-lint:
    name: Quality checks via SonarCloud with coverage report
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python_versions) }}

  steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: Load Pip Cache (when it exists)
        uses: actions/cache@v4
        id: cached-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip

      - name: Install Fresh Linters
        if: steps.cached-pip.outputs.cache-hit != 'true'
        run: python -m pip install black flake8 isort

      - name: Run Linters
      - run: |
          flake8 .
          black . --check
          isort .
