name: Sonar Quality Control

on:
  workflow_call:
    inputs:
      # Optional
      coverage_report_name:
        type: string
        default: coverage.xml
    secrets:
      # Required
      sonar_token:
        required: true

jobs:
  quality-control-sonar:
    name: Quality checks via SonarCloud with coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.coverage_report_name }}

      - name: SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





